Repository capstone-prs/donation-app, pull requests merged in 2023-11, with the labels that each got.

#5 Add initial scaffold for all pages
  ambag-co/public/sample.jpg
  ambag-co/public/sample2.jpg
  ambag-co/public/system-icon.png
  ambag-co/src/components/DonorAvatar.vue
  ambag-co/src/components/EssentialLink.vue
  ambag-co/src/components/ExampleComponent.vue
  ambag-co/src/components/FeatureComponent.vue
  ambag-co/src/components/ProjectComponent.vue
  ambag-co/src/components/buttons/GoogleSignIn.vue
  ambag-co/src/layouts/HeaderLayout.vue
  ambag-co/src/layouts/MainLayout.vue
  ambag-co/src/pages/DonorPage.vue
  ambag-co/src/pages/HomePage.vue
  ambag-co/src/pages/IndexPage.vue
  ambag-co/src/pages/ProfilePage.vue
  ambag-co/src/pages/ProjectPage.vue
  ambag-co/src/pages/SignIn.vue
  ambag-co/src/pages/SignUp.vue
  ambag-co/src/router/routes.ts
Labels: Initial

#7 🚧 Fixes Login and SignUp Redirect
  ambag-co/src/components/buttons/GoogleSignIn.vue
  ambag-co/src/pages/SignUp.vue
Labels: enhancement

#8 Added Profile page
  ambag-co/src/pages/ProfilePage.vue
  ambag-co/src/utils/firebase.ts
Labels: enhancement

#9 🚧 Fixes disappearing user info when reloading
  ambag-co/quasar.config.js
  ambag-co/src/pages/ProfilePage.vue
Labels: enhancement

#10 Initially integrate smart contract
  ambag-co/package-lock.json
  ambag-co/package.json
  ambag-co/quasar.config.js
  ambag-co/src/pages/HomePage.vue
  ambag-co/src/pages/ProfilePage.vue
  ambag-co/src/pages/USDT_contract_ABI.json
  ambag-co/tsconfig.json
Labels: enhancement, Initial

#14 Add Programs
  ambag-co/src/pages/AddProject.vue
  ambag-co/src/pages/HomePage.vue
  ambag-co/src/pages/ProjectPage.vue
  ambag-co/src/types/Users.ts
  ambag-co/src/utils/firebase.ts
Labels: enhancement
